version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  adonis-app:
    build: ./backend
    command: sh -c "node ace migration:fresh && node ace db:seed && node ace serve"
    ports:
      - "3333:3333"
    depends_on:
      - postgres

  sveltekit-app:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - adonis-app

  nginx-proxy:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certificate.crt:/etc/nginx/certificate.crt:ro
      - ./nginx/private.key:/etc/nginx/private.key:ro
    depends_on:
      - adonis-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge